# This is a basic workflow to help you get started with Actions

name: Execução de testes

# Controls when the workflow will run
on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 22
        uses: actions/setup-java@v2
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Build
        run: ./gradlew build

      - name: Tests
        run: ./gradlew test

      - name: JaCoCo report
        run: ./gradlew jacocoTestReport

      - name: Archive test reports
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: build/reports/jacoco/test/html/
